<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="ja" sourcelanguage="en">
  <context>
    <name>@default</name>
    <message>
      <source>TOP_CLEAR_ALL</source>
      <translation>すべて消去します。</translation>
    </message>
    <message>
      <source>STB_CLEAR_ALL</source>
      <translation>すべての行のテキストをクリア</translation>
    </message>
    <message>
      <source>STB_SAVE_FILE</source>
      <translation>テキスト ファイルを保存します。</translation>
    </message>
    <message>
      <source>TOP_SAVE_FILE</source>
      <translation>テキスト ファイルを保存します。</translation>
    </message>
    <message>
      <source>MEN_LIGHT</source>
      <translation>LIGHT</translation>
    </message>
    <message>
      <source>MEN_LOAD_FILE</source>
      <translation>テキスト ファイルを開く</translation>
    </message>
    <message>
      <source>WRN_UNKNOWN_COMMAND</source>
      <translation>不明なコマンド ！</translation>
    </message>
    <message>
      <source>BUT_OK</source>
      <translation>わかりました(&amp;O)</translation>
    </message>
    <message>
      <source>WRN_ADD_FAILED</source>
      <translation>行を挿入できません。</translation>
    </message>
    <message>
      <source>STB_DISPLAY_LINE</source>
      <translation>選択した行を表示します。</translation>
    </message>
    <message>
      <source>TOP_DISPLAY_LINE</source>
      <translation>行を表示します。</translation>
    </message>
    <message>
      <source>MEN_DISPLAY_LINE</source>
      <translation>選択した行を表示します。</translation>
    </message>
    <message>
      <source>STB_ERASE_LINE</source>
      <translation>選択した行を削除</translation>
    </message>
    <message>
      <source>TOP_ERASE_LINE</source>
      <translation>行を削除</translation>
    </message>
    <message>
      <source>MEN_ERASE_LINE</source>
      <translation>選択した行を削除</translation>
    </message>
    <message>
      <source>STB_EDIT_LINE</source>
      <translation>選択した行を編集</translation>
    </message>
    <message>
      <source>WRN_EDIT_FAILED</source>
      <translation>行を編集することができません。</translation>
    </message>
    <message>
      <source>WRN_DUMP_FAILED</source>
      <translation>ファイルを保存することはできません ！</translation>
    </message>
    <message>
      <source>WRN_LOAD_FAILED</source>
      <translation>ファイルを開くことができません。</translation>
    </message>
    <message>
      <source>TOP_EDIT_LINE</source>
      <translation>行を編集</translation>
    </message>
    <message>
      <source>MEN_CLEAR_ALL</source>
      <translation>すべて消去します。</translation>
    </message>
    <message>
      <source>MEN_FILE</source>
      <translation>ファイル(&amp;F)</translation>
    </message>
    <message>
      <source>LIGHT_ROOT_TOOLTIP</source>
      <translation>LIGHTモジュール ルート オブジェクト</translation>
    </message>
    <message>
      <source>LIGHT_LIGHT</source>
      <translation>LIGHT</translation>
    </message>
    <message>
      <source>MEN_SAVE_FILE</source>
      <translation>テキスト ファイルを保存します。</translation>
    </message>
    <message>
      <source>WRN_WARNING</source>
      <translation>注意 ！</translation>
    </message>
    <message>
      <source>WRN_DELETE_FAILED</source>
      <translation>行を削除できません</translation>
    </message>
    <message>
      <source>WRN_SELECT_LINE</source>
      <translation>不適切な選択 ！</translation>
    </message>
    <message>
      <source>TOP_LOAD_FILE</source>
      <translation>テキスト ファイルを開く</translation>
    </message>
    <message>
      <source>TOP_ADD_LINE</source>
      <translation>行を追加します。</translation>
    </message>
    <message>
      <source>MEN_DEL_LINE</source>
      <translation>行を削除</translation>
    </message>
    <message>
      <source>STB_LOAD_FILE</source>
      <translation>テキスト ファイルを開く</translation>
    </message>
    <message>
      <source>STB_ADD_LINE</source>
      <translation>選択した行の前に新しい行を挿入</translation>
    </message>
    <message>
      <source>LIGHT_PARAGRAPH</source>
      <translation>段落</translation>
    </message>
    <message>
      <source>TOP_DEL_LINE</source>
      <translation>行を削除</translation>
    </message>
    <message>
      <source>MEN_ADD_LINE</source>
      <translation>新しい行を挿入</translation>
    </message>
    <message>
      <source>LIGHT_LINE</source>
      <translation>Line</translation>
    </message>
    <message>
      <source>STB_DEL_LINE</source>
      <translation>選択した行を削除</translation>
    </message>
    <message>
      <source>MEN_EDIT_LINE</source>
      <translation>選択した行を編集</translation>
    </message>
    <message>
      <source>MEN_SHOW_TRACE</source>
      <translation>トレースを表示する.</translation>
    </message>
    <message>
      <source>TOP_SHOW_TRACE</source>
      <translation>トレースを表示します。</translation>
    </message>
    <message>
      <source>STB_SHOW_TRACE</source>
      <translation>トレースを表示します。</translation>
    </message>
    <message>
      <source>MEN_RESTART_TRACE</source>
      <translation>トレースを再初期化します。</translation>
    </message>
    <message>
      <source>TOP_RESTART_TRACE</source>
      <translation>トレースを再初期化します。</translation>
    </message>
    <message>
      <source>STB_RESTART_TRACE</source>
      <translation>トレースを再初期化します。</translation>
    </message>
  </context>
  <context>
    <name>PVGUI_ViewManager</name>
    <message>
      <source>PARAVIEW_VIEW_TITLE</source>
      <translation>シーン ParaView: %M - visualisateur: %V</translation>
    </message>
  </context>
  <context>
    <name>PVGUI_Module</name>
    <message>
      <source>TTL_PIPELINE_BROWSER</source>
      <translation>パイプのブラウザー</translation>
    </message>
    <message>
      <source>TTL_OBJECT_INSPECTOR</source>
      <translation>オブジェクト インスペクター</translation>
    </message>
    <message>
      <source>TTL_MUTLI_BLOCK_INSPECTOR</source>
      <translation>TTL_MUTLI_BLOCK_INSPECTOR</translation>
    </message>
    <message>
      <source>TTL_COLOR_MAP_EDITOR</source>
      <translation>TTL_COLOR_MAP_EDITOR</translation>
    </message>
    <message>
      <source>TTL_DISPLAY</source>
      <translation>表示</translation>
    </message>
    <message>
      <source>TTL_INFORMATION</source>
      <translation>情報</translation>
    </message>
    <message>
      <source>TTL_STATISTICS_VIEW</source>
      <translation>統計情報の表示</translation>
    </message>
    <message>
      <source>TTL_ANIMATION_INSPECTOR</source>
      <translation>アニメーションの検査官</translation>
    </message>
    <message>
      <source>TTL_LOOKMARK_BROWSER</source>
      <translation>ビジュアル ブック マーク ブラウザー</translation>
    </message>
    <message>
      <source>TTL_LOOKMARK_INSPECTOR</source>
      <translation>ビジュアル ブック マーク ブラウザー</translation>
    </message>
    <message>
      <source>TTL_COMPARATIVE_VIEW_INSPECTOR</source>
      <translation>比較ビュー ブラウザー</translation>
    </message>
    <message>
      <source>TTL_ANIMATION_VIEW</source>
      <translation>アニメーションの概要</translation>
    </message>
    <message>
      <source>TTL_SELECTION_INSPECTOR</source>
      <translation>ブラウザー選択</translation>
    </message>
    <message>
      <source>TTL_COLLABORATIVE_DOCK</source>
      <translation>コラボレーション パネル</translation>
    </message>
    <message>
      <source>TTL_MEMORY_INSPECTOR</source>
      <translation>メモリ使用量</translation>
    </message>
    <message>
      <source>TOP_OPEN_FILE</source>
      <translation>ファイル ParaView を開く</translation>
    </message>
    <message>
      <source>MEN_OPEN</source>
      <translation>インポート...(&amp;I)</translation>
    </message>
    <message>
      <source>MEN_OPEN_FILE</source>
      <translation>ParaView ファイルを開く...</translation>
    </message>
    <message>
      <source>STB_OPEN_FILE</source>
      <translation>ファイル ParaView を開く</translation>
    </message>
    <message>
      <source>MEN_RECENT_FILES</source>
      <translation>ParaView の最近のファイル</translation>
    </message>
    <message>
      <source>TOP_LOAD_STATE</source>
      <translation>レポートを開く</translation>
    </message>
    <message>
      <source>MEN_LOAD_STATE</source>
      <translation>状態を開く...(&amp;L)</translation>
    </message>
    <message>
      <source>STB_LOAD_STATE</source>
      <translation>レポートを開く</translation>
    </message>
    <message>
      <source>TOP_SAVE_STATE</source>
      <translation>状態を保存します。</translation>
    </message>
    <message>
      <source>MEN_SAVE_STATE</source>
      <translation>状態を保存しています.(&amp;S)</translation>
    </message>
    <message>
      <source>STB_SAVE_STATE</source>
      <translation>状態を保存します。</translation>
    </message>
    <message>
      <source>TOP_SAVE_DATA</source>
      <translation>データを保存します。</translation>
    </message>
    <message>
      <source>MEN_SAVE_DATA</source>
      <translation>データを保存.</translation>
    </message>
    <message>
      <source>STB_SAVE_DATA</source>
      <translation>データを保存します。</translation>
    </message>
    <message>
      <source>TOP_SAVE_SCREENSHOT</source>
      <translation>スナップショットを保存します。</translation>
    </message>
    <message>
      <source>MEN_SAVE_SCREENSHOT</source>
      <translation>スナップショットを保存.</translation>
    </message>
    <message>
      <source>STB_SAVE_SCREENSHOT</source>
      <translation>スナップショットを保存します。</translation>
    </message>
    <message>
      <source>TOP_EXPORT</source>
      <translation>エクスポート</translation>
    </message>
    <message>
      <source>MEN_EXPORT</source>
      <translation>エクスポート...</translation>
    </message>
    <message>
      <source>STB_EXPORT</source>
      <translation>エクスポート</translation>
    </message>
    <message>
      <source>TOP_SAVE_ANIMATION</source>
      <translation>アニメーションを保存します。</translation>
    </message>
    <message>
      <source>MEN_SAVE_ANIMATION</source>
      <translation>アニメーションを保存.(&amp;A)</translation>
    </message>
    <message>
      <source>STB_SAVE_ANIMATION</source>
      <translation>アニメーションを保存します。</translation>
    </message>
    <message>
      <source>TOP_SAVE_GEOMETRY</source>
      <translation>ジオメトリを保存します。</translation>
    </message>
    <message>
      <source>MEN_SAVE_GEOMETRY</source>
      <translation>ジオメトリを保存します。(&amp;G)</translation>
    </message>
    <message>
      <source>STB_SAVE_GEOMETRY</source>
      <translation>ジオメトリを保存します。</translation>
    </message>
    <message>
      <source>TOP_CONNECT</source>
      <translation>接続</translation>
    </message>
    <message>
      <source>MEN_CONNECT</source>
      <translation>接続...(&amp;C)</translation>
    </message>
    <message>
      <source>STB_CONNECT</source>
      <translation>サーバーへの接続します。</translation>
    </message>
    <message>
      <source>TOP_DISCONNECT</source>
      <translation>アンロード</translation>
    </message>
    <message>
      <source>MEN_DISCONNECT</source>
      <translation>アンロード(&amp;D)</translation>
    </message>
    <message>
      <source>STB_DISCONNECT</source>
      <translation>サーバーから切断します。</translation>
    </message>
    <message>
      <source>TOP_UNDO</source>
      <translation>キャンセル</translation>
    </message>
    <message>
      <source>MEN_UNDO</source>
      <translation>キャンセル(&amp;U)</translation>
    </message>
    <message>
      <source>MEN_CANTUNDO</source>
      <translation>アンドゥできません</translation>
    </message>
    <message>
      <source>MEN_UNDO_ACTION</source>
      <translation>%1 をキャンセルします。(&amp;U)</translation>
    </message>
    <message>
      <source>MEN_UNDO_ACTION_TIP</source>
      <translation>%1 をキャンセルします。</translation>
    </message>
    <message>
      <source>STB_UNDO</source>
      <translation>最後の操作をキャンセルします。</translation>
    </message>
    <message>
      <source>INF_APP_UNDOACTIONS</source>
      <translation>キャンセル アクション (s) %1</translation>
    </message>
    <message>
      <source>TOP_REDO</source>
      <translation>復元</translation>
    </message>
    <message>
      <source>MEN_REDO</source>
      <translation>復元(&amp;R)</translation>
    </message>
    <message>
      <source>MEN_CANTREDO</source>
      <translation>リドゥできません</translation>
    </message>
    <message>
      <source>MEN_REDO_ACTION</source>
      <translation>%1 を復元します。(&amp;R)</translation>
    </message>
    <message>
      <source>MEN_REDO_ACTION_TIP</source>
      <translation>%1 を復元します。</translation>
    </message>
    <message>
      <source>STB_REDO</source>
      <translation>最後の操作を復元します。</translation>
    </message>
    <message>
      <source>INF_APP_REDOACTIONS</source>
      <translation>%1 アクション (s) の復元します。</translation>
    </message>
    <message>
      <source>TOP_CAMERA_UNDO</source>
      <translation>カメラをアンドゥ</translation>
    </message>
    <message>
      <source>MEN_CAMERA_UNDO</source>
      <translation>カメラをアンドゥ</translation>
    </message>
    <message>
      <source>MEN_CANT_CAMERA_UNDO</source>
      <translation>カメラをアンドゥできません</translation>
    </message>
    <message>
      <source>MEN_CAMERA_UNDO_ACTION</source>
      <translation>%1 をキャンセルします。(&amp;n)</translation>
    </message>
    <message>
      <source>MEN_CAMERA_UNDO_ACTION_TIP</source>
      <translation>%1 をキャンセルします。</translation>
    </message>
    <message>
      <source>STB_CAMERA_UNDO</source>
      <translation>カメラの最後の操作をキャンセルします。</translation>
    </message>
    <message>
      <source>INF_APP_CAMERA_UNDOACTIONS</source>
      <translation>キャンセル アクション カメラ (s) %1</translation>
    </message>
    <message>
      <source>TOP_CAMERA_REDO</source>
      <translation>カメラをリドゥ</translation>
    </message>
    <message>
      <source>MEN_CAMERA_REDO</source>
      <translation>カメラをリドゥ</translation>
    </message>
    <message>
      <source>MEN_CANT_CAMERA_REDO</source>
      <translation>カメラをリドゥできません</translation>
    </message>
    <message>
      <source>MEN_CAMERA_REDO_ACTION</source>
      <translation>%1 を復元します。(&amp;e)</translation>
    </message>
    <message>
      <source>MEN_CAMERA_REDO_ACTION_TIP</source>
      <translation>%1 を復元します。</translation>
    </message>
    <message>
      <source>STB_CAMERA_REDO</source>
      <translation>カメラの最後の操作を復元します。</translation>
    </message>
    <message>
      <source>INF_APP_CAMERA_REDOACTIONS</source>
      <translation>%1 アクション （秒） カメラの復元します。</translation>
    </message>
    <message>
      <source>TOP_CHANGE_INPUT</source>
      <translation>インプットを変更...</translation>
    </message>
    <message>
      <source>MEN_FIND_DATA</source>
      <translation>データを見つける.</translation>
    </message>
    <message>
      <source>MEN_CHANGE_INPUT</source>
      <translation>インプットを変更...(&amp;I)</translation>
    </message>
    <message>
      <source>STB_CHANGE_INPUT</source>
      <translation>フィルターのエントリを変更します。</translation>
    </message>
    <message>
      <source>INF_APP_CHANGE_INPUTACTIONS</source>
      <translation>フィルターのエントリを変更する.</translation>
    </message>
    <message>
      <source>MEN_IGNORE_TIME</source>
      <translation>時間を無視します。</translation>
    </message>
    <message>
      <source>TOP_IGNORE_TIME</source>
      <translation>時間を無視します。</translation>
    </message>
    <message>
      <source>STB_IGNORE_TIME</source>
      <translation>このソース時刻にフィルター アニメーションを無視</translation>
    </message>
    <message>
      <source>TOP_DELETE</source>
      <translation>削除</translation>
    </message>
    <message>
      <source>MEN_DELETE</source>
      <translation>削除(&amp;D)</translation>
    </message>
    <message>
      <source>STB_DELETE</source>
      <translation>削除</translation>
    </message>
    <message>
      <source>TOP_DELETE_ALL</source>
      <translation>すべて削除</translation>
    </message>
    <message>
      <source>MEN_DELETE_ALL</source>
      <translation>すべて削除</translation>
    </message>
    <message>
      <source>STB_DELETE_ALL</source>
      <translation>すべて削除</translation>
    </message>
    <message>
      <source>TOP_INTERACT</source>
      <translation>対話</translation>
    </message>
    <message>
      <source>MEN_INTERACT</source>
      <translation>対話</translation>
    </message>
    <message>
      <source>STB_INTERACT</source>
      <translation>対話</translation>
    </message>
    <message>
      <source>TOP_SELECT_CELLS_ON</source>
      <translation>セルを選択します。</translation>
    </message>
    <message>
      <source>MEN_SELECT_CELLS_ON</source>
      <translation>セルを選択します。</translation>
    </message>
    <message>
      <source>STB_SELECT_CELLS_ON</source>
      <translation>セルを選択します。</translation>
    </message>
    <message>
      <source>TOP_SELECT_POINTS_ON</source>
      <translation>上のポイントを選択します。</translation>
    </message>
    <message>
      <source>MEN_SELECT_POINTS_ON</source>
      <translation>上のポイントを選択します。</translation>
    </message>
    <message>
      <source>STB_SELECT_POINTS_ON</source>
      <translation>上のポイントを選択します。</translation>
    </message>
    <message>
      <source>TOP_SELECT_CELLS_THROUGH</source>
      <translation>細胞を選択.</translation>
    </message>
    <message>
      <source>MEN_SELECT_CELLS_THROUGH</source>
      <translation>細胞を選択.</translation>
    </message>
    <message>
      <source>STB_SELECT_CELLS_THROUGH</source>
      <translation>細胞を選択.</translation>
    </message>
    <message>
      <source>TOP_SELECT_POINTS_THROUGH</source>
      <translation>ポイントを選択.</translation>
    </message>
    <message>
      <source>MEN_SELECT_POINTS_THROUGH</source>
      <translation>ポイントを選択.</translation>
    </message>
    <message>
      <source>STB_SELECT_POINTS_THROUGH</source>
      <translation>ポイントを選択.</translation>
    </message>
    <message>
      <source>TOP_SELECT_BLOCK</source>
      <translation>ブロックを選択します。</translation>
    </message>
    <message>
      <source>MEN_SELECT_BLOCK</source>
      <translation>ブロックを選択します。</translation>
    </message>
    <message>
      <source>STB_SELECT_BLOCK</source>
      <translation>ブロックを選択します。</translation>
    </message>
    <message>
      <source>TOP_SETTINGS</source>
      <translation>オプション</translation>
    </message>
    <message>
      <source>MEN_SETTINGS</source>
      <translation>オプション</translation>
    </message>
    <message>
      <source>STB_SETTINGS</source>
      <translation>オプション</translation>
    </message>
    <message>
      <source>TOP_VIEW_SETTINGS</source>
      <translation>可視化オプション</translation>
    </message>
    <message>
      <source>MEN_VIEW_SETTINGS</source>
      <translation>可視化のオプション.</translation>
    </message>
    <message>
      <source>STB_VIEW_SETTINGS</source>
      <translation>可視化オプション</translation>
    </message>
    <message>
      <source>MEN_CAMERA</source>
      <translation>カメラ</translation>
    </message>
    <message>
      <source>TOP_RESET_CAMERA</source>
      <translation>カメラをリセットします。</translation>
    </message>
    <message>
      <source>MEN_RESET_CAMERA</source>
      <translation>リセット(&amp;R)</translation>
    </message>
    <message>
      <source>STB_RESET_CAMERA</source>
      <translation>カメラをリセットします。</translation>
    </message>
    <message>
      <source>TOP_+X</source>
      <translation>X ビューの方向を初期化します。</translation>
    </message>
    <message>
      <source>MEN_+X</source>
      <translation>+X</translation>
    </message>
    <message>
      <source>STB_+X</source>
      <translation>X ビューの方向を初期化します。</translation>
    </message>
    <message>
      <source>TOP_-X</source>
      <translation>ビュー - X の方向を初期化します。</translation>
    </message>
    <message>
      <source>MEN_-X</source>
      <translation>-X</translation>
    </message>
    <message>
      <source>STB_-X</source>
      <translation>ビュー - X の方向を初期化します。</translation>
    </message>
    <message>
      <source>TOP_+Y</source>
      <translation>Y ビューの方向を初期化します。</translation>
    </message>
    <message>
      <source>MEN_+Y</source>
      <translation>+Y</translation>
    </message>
    <message>
      <source>STB_+Y</source>
      <translation>Y ビューの方向を初期化します。</translation>
    </message>
    <message>
      <source>TOP_-Y</source>
      <translation>表示する-Y の方向を初期化します。</translation>
    </message>
    <message>
      <source>MEN_-Y</source>
      <translation>-Y</translation>
    </message>
    <message>
      <source>STB_-Y</source>
      <translation>表示する-Y の方向を初期化します。</translation>
    </message>
    <message>
      <source>TOP_+Z</source>
      <translation>Z ビューの方向を初期化します。</translation>
    </message>
    <message>
      <source>MEN_+Z</source>
      <translation>+Z</translation>
    </message>
    <message>
      <source>STB_+Z</source>
      <translation>Z ビューの方向を初期化します。</translation>
    </message>
    <message>
      <source>TOP_-Z</source>
      <translation>Z ビューの方向を初期化します。</translation>
    </message>
    <message>
      <source>MEN_-Z</source>
      <translation>-Z</translation>
    </message>
    <message>
      <source>STB_-Z</source>
      <translation>Z ビューの方向を初期化します。</translation>
    </message>
    <message>
      <source>TOP_SHOW_CENTER</source>
      <translation>センターを表示します。</translation>
    </message>
    <message>
      <source>MEN_SHOW_CENTER</source>
      <translation>センターを表示します。</translation>
    </message>
    <message>
      <source>PRP_APP_SHOW_CENTER</source>
      <translation>回転の中心を表示</translation>
    </message>
    <message>
      <source>TOP_RESET_CENTER</source>
      <translation>中心部をリセットします。</translation>
    </message>
    <message>
      <source>MEN_RESET_CENTER</source>
      <translation>中心部をリセットします。</translation>
    </message>
    <message>
      <source>STB_RESET_CENTER</source>
      <translation>回転の中心をリセットします。</translation>
    </message>
    <message>
      <source>TOP_PICK_CENTER</source>
      <translation>中心を選択します。</translation>
    </message>
    <message>
      <source>MEN_PICK_CENTER</source>
      <translation>中心を選択します。</translation>
    </message>
    <message>
      <source>PRP_APP_PICK_CENTER</source>
      <translation>回転の中心を選択するには、マウスをクリックします。</translation>
    </message>
    <message>
      <source>TOP_SHOW_COLOR_LEGEND</source>
      <translation>色の凡例を表示します。</translation>
    </message>
    <message>
      <source>MEN_SHOW_COLOR_LEGEND</source>
      <translation>色の凡例を表示します。</translation>
    </message>
    <message>
      <source>PRP_APP_SHOW_COLOR_LEGEND</source>
      <translation>色の凡例を表示します。</translation>
    </message>
    <message>
      <source>TOP_EDIT_COLOR_MAP</source>
      <translation>カラー パレットを編集します。</translation>
    </message>
    <message>
      <source>MEN_EDIT_COLOR_MAP</source>
      <translation>カラー パレットを編集します。</translation>
    </message>
    <message>
      <source>PRP_APP_EDIT_COLOR_MAP</source>
      <translation>カラー パレットを編集します。</translation>
    </message>
    <message>
      <source>TOP_RESET_RANGE</source>
      <translation>データの範囲に戻る</translation>
    </message>
    <message>
      <source>MEN_RESET_RANGE</source>
      <translation>範囲をリセットします。</translation>
    </message>
    <message>
      <source>PRP_APP_RESET_RANGE</source>
      <translation>データの範囲に戻る</translation>
    </message>
    <message>
      <source>MEN_DESK_SOURCES</source>
      <translation>ソース(&amp;S)</translation>
    </message>
    <message>
      <source>MEN_DESK_FILTERS</source>
      <translation>フィルター(&amp;i)</translation>
    </message>
    <message>
      <source>MEN_DESK_ANIMATION</source>
      <translation>アニメーション(&amp;n)</translation>
    </message>
    <message>
      <source>TOP_FIRST_FRAME</source>
      <translation>最初のフレームワーク</translation>
    </message>
    <message>
      <source>MEN_FIRST_FRAME</source>
      <translation>最初のフレームワーク(&amp;F)</translation>
    </message>
    <message>
      <source>STB_FIRST_FRAME</source>
      <translation>最初のフレームワーク</translation>
    </message>
    <message>
      <source>TOP_PREVIOUS_FRAME</source>
      <translation>以前の枠組み</translation>
    </message>
    <message>
      <source>MEN_PREVIOUS_FRAME</source>
      <translation>以前の枠組み(&amp;v)</translation>
    </message>
    <message>
      <source>STB_PREVIOUS_FRAME</source>
      <translation>以前の枠組み</translation>
    </message>
    <message>
      <source>TOP_PLAY</source>
      <translation>再生</translation>
    </message>
    <message>
      <source>MEN_PLAY</source>
      <translation>再生(&amp;P)</translation>
    </message>
    <message>
      <source>STB_PLAY</source>
      <translation>再生</translation>
    </message>
    <message>
      <source>TOP_NEXT_FRAME</source>
      <translation>次のフレームワーク</translation>
    </message>
    <message>
      <source>MEN_NEXT_FRAME</source>
      <translation>次のフレームワーク(&amp;N)</translation>
    </message>
    <message>
      <source>STB_NEXT_FRAME</source>
      <translation>次のフレームワーク</translation>
    </message>
    <message>
      <source>TOP_LAST_FRAME</source>
      <translation>最後のフレーム</translation>
    </message>
    <message>
      <source>MEN_LAST_FRAME</source>
      <translation>最後のフレーム(&amp;L)</translation>
    </message>
    <message>
      <source>STB_LAST_FRAME</source>
      <translation>最後のフレーム</translation>
    </message>
    <message>
      <source>TOP_LOOP</source>
      <translation>ループ</translation>
    </message>
    <message>
      <source>MEN_LOOP</source>
      <translation>ループ(&amp;o)</translation>
    </message>
    <message>
      <source>PRP_APP_LOOP</source>
      <translation>ループ</translation>
    </message>
    <message>
      <source>MEN_DESK_TOOLS</source>
      <translation>ツール(&amp;T)</translation>
    </message>
    <message>
      <source>TOP_CREATE_CUSTOM_FILTER</source>
      <translation>カスタム フィルターを作成します。</translation>
    </message>
    <message>
      <source>MEN_CREATE_CUSTOM_FILTER</source>
      <translation>カスタムフィルターの作成...(&amp;C)</translation>
    </message>
    <message>
      <source>STB_CREATE_CUSTOM_FILTER</source>
      <translation>カスタム フィルターを作成します。</translation>
    </message>
    <message>
      <source>TOP_MANAGE_CUSTOM_FILTERS</source>
      <translation>カスタム フィルターを管理します。</translation>
    </message>
    <message>
      <source>MEN_MANAGE_CUSTOM_FILTERS</source>
      <translation>カスタム フィルターの管理...(&amp;M)</translation>
    </message>
    <message>
      <source>STB_MANAGE_CUSTOM_FILTERS</source>
      <translation>カスタム フィルターを管理します。</translation>
    </message>
    <message>
      <source>TOP_CREATE_LOOKMARK</source>
      <translation>Lookmarkを作成</translation>
    </message>
    <message>
      <source>MEN_CREATE_LOOKMARK</source>
      <translation>Lookmarkを作成</translation>
    </message>
    <message>
      <source>STB_CREATE_LOOKMARK</source>
      <translation>Lookmarkを作成</translation>
    </message>
    <message>
      <source>TOP_MANAGE_LINKS</source>
      <translation>リンクを管理します。</translation>
    </message>
    <message>
      <source>MEN_MANAGE_LINKS</source>
      <translation>リンクを管理...</translation>
    </message>
    <message>
      <source>STB_MANAGE_LINKS</source>
      <translation>リンクを管理します。</translation>
    </message>
    <message>
      <source>TOP_ADD_CAMERA_LINK</source>
      <translation>カメラのリンクを追加します。</translation>
    </message>
    <message>
      <source>MEN_ADD_CAMERA_LINK</source>
      <translation>カメラのリンクを追加...</translation>
    </message>
    <message>
      <source>STB_ADD_CAMERA_LINK</source>
      <translation>カメラのリンクを追加します。</translation>
    </message>
    <message>
      <source>WRN_ADD_CAMERA_LINK</source>
      <translation>... のカメラからのリンクの追加: アクティブなレンダリング モジュールがないです。</translation>
    </message>
    <message>
      <source>TOP_MANAGE_PLUGINS</source>
      <translation>プラグイン ・拡張機能を管理します。</translation>
    </message>
    <message>
      <source>MEN_MANAGE_PLUGINS</source>
      <translation>プラグインの管理...</translation>
    </message>
    <message>
      <source>STB_MANAGE_PLUGINS</source>
      <translation>プラグイン ・拡張機能を管理します。</translation>
    </message>
    <message>
      <source>TOP_DUMP_WIDGET_NAMES</source>
      <translation>Windows の名前を覚えてください。</translation>
    </message>
    <message>
      <source>MEN_DUMP_WIDGET_NAMES</source>
      <translation>Windows の名前を覚えてください。(&amp;D)</translation>
    </message>
    <message>
      <source>STB_DUMP_WIDGET_NAMES</source>
      <translation>Windows の名前を覚えてください。</translation>
    </message>
    <message>
      <source>TOP_RECORD_TEST</source>
      <translation>テストを登録します。</translation>
    </message>
    <message>
      <source>MEN_RECORD_TEST</source>
      <translation>テストを登録します。(&amp;R)</translation>
    </message>
    <message>
      <source>STB_RECORD_TEST</source>
      <translation>テストを登録します。</translation>
    </message>
    <message>
      <source>TOP_RECORD_TEST_SCREENSHOT</source>
      <translation>テストのスナップショットを保存します。</translation>
    </message>
    <message>
      <source>MEN_RECORD_TEST_SCREENSHOT</source>
      <translation>テストのスナップショットを保存します。(&amp;T)</translation>
    </message>
    <message>
      <source>STB_RECORD_TEST_SCREENSHOT</source>
      <translation>テストのスナップショットを保存します。</translation>
    </message>
    <message>
      <source>TOP_PLAY_TEST</source>
      <translation>テストを再生します。</translation>
    </message>
    <message>
      <source>MEN_PLAY_TEST</source>
      <translation>テストを再生します。</translation>
    </message>
    <message>
      <source>STB_PLAY_TEST</source>
      <translation>テストを再生します。</translation>
    </message>
    <message>
      <source>TOP_MAX_WINDOW_SIZE</source>
      <translation>ビューのサイズをロックします。</translation>
    </message>
    <message>
      <source>MEN_MAX_WINDOW_SIZE</source>
      <translation>ビューのサイズをロックします。</translation>
    </message>
    <message>
      <source>MEN_CUSTOM_WINDOW_SIZE</source>
      <translation>カスタム ビューのサイズをロック</translation>
    </message>
    <message>
      <source>PRP_APP_MAX_WINDOW_SIZE</source>
      <translation>ビューのサイズをロックします。</translation>
    </message>
    <message>
      <source>TOP_TIMER_LOG</source>
      <translation>タイマーのジャーナル</translation>
    </message>
    <message>
      <source>MEN_TIMER_LOG</source>
      <translation>タイマーのジャーナル(&amp;L)</translation>
    </message>
    <message>
      <source>STB_TIMER_LOG</source>
      <translation>タイマーのジャーナル</translation>
    </message>
    <message>
      <source>TOP_OUTPUT_WINDOW</source>
      <translation>出力ウィンドウ</translation>
    </message>
    <message>
      <source>MEN_OUTPUT_WINDOW</source>
      <translation>出力ウィンドウ(&amp;O)</translation>
    </message>
    <message>
      <source>STB_OUTPUT_WINDOW</source>
      <translation>出力ウィンドウ</translation>
    </message>
    <message>
      <source>TOP_PYTHON_SHELL</source>
      <translation>Python パッケージ</translation>
    </message>
    <message>
      <source>MEN_PYTHON_SHELL</source>
      <translation>Python パッケージ(&amp;S)</translation>
    </message>
    <message>
      <source>STB_PYTHON_SHELL</source>
      <translation>Python パッケージ</translation>
    </message>
    <message>
      <source>TOP_ABOUT</source>
      <translation>ParaView について</translation>
    </message>
    <message>
      <source>MEN_ABOUT</source>
      <translation>ParaView について.</translation>
    </message>
    <message>
      <source>MEN_PVHELP</source>
      <translation>ParaView のヘルプ</translation>
    </message>
    <message>
      <source>STB_ABOUT</source>
      <translation>ParaView について</translation>
    </message>
    <message>
      <source>TOP_PARAVIEW_HELP</source>
      <translation>手動のユーザー ParaView の</translation>
    </message>
    <message>
      <source>MEN_PARAVIEW_HELP</source>
      <translation>ParaView のヘルプ</translation>
    </message>
    <message>
      <source>STB_PARAVIEW_HELP</source>
      <translation>ParaView のリファレンス ドキュメント</translation>
    </message>
    <message>
      <source>TOP_ENABLE_TOOLTIPS</source>
      <translation>ツールヒントを有効にします。</translation>
    </message>
    <message>
      <source>MEN_ENABLE_TOOLTIPS</source>
      <translation>ツールヒントを有効にします。</translation>
    </message>
    <message>
      <source>STB_ENABLE_TOOLTIPS</source>
      <translation>ツールヒントを有効にします。</translation>
    </message>
    <message>
      <source>STB_PREACCEPT</source>
      <translation>更新...</translation>
    </message>
    <message>
      <source>STB_POSTACCEPT</source>
      <translation>準備完了</translation>
    </message>
    <message>
      <source>TOOL_ACTIVE_VARIABLE_CONTROLS</source>
      <translation>変数のコントロールを有効にします。</translation>
    </message>
    <message>
      <source>TOOL_CAMERA_CONTROLS</source>
      <translation>カメラ コントロール</translation>
    </message>
    <message>
      <source>TOOL_CENTER_AXES_CONTROLS</source>
      <translation>軸コントロールを中心としてください。</translation>
    </message>
    <message>
      <source>TOOL_COMMON_FILTERS</source>
      <translation>共通フィルター</translation>
    </message>
    <message>
      <source>TOOL_CURRENT_TIME_CONTROLS</source>
      <translation>現在の時刻のコントロール</translation>
    </message>
    <message>
      <source>TOOL_LOOKMARKS</source>
      <translation>Visual のブックマーク</translation>
    </message>
    <message>
      <source>TOOL_MAIN_CONTROLS</source>
      <translation>メイン コントロール</translation>
    </message>
    <message>
      <source>TOOL_REPRESENTATION</source>
      <translation>表現</translation>
    </message>
    <message>
      <source>TOOL_SELECTION_CONTROLS</source>
      <translation>選択コントロール</translation>
    </message>
    <message>
      <source>TOOL_UNDOREDO_CONTROLS</source>
      <translation>コントロールの取り消しとやり直し</translation>
    </message>
    <message>
      <source>TOOL_VCR_CONTROLS</source>
      <translation>VCR のコントロール</translation>
    </message>
    <message>
      <source>PREF_STOP_TRACE</source>
      <translation>（のみのための次のセッション) のトレースを有効に</translation>
    </message>
    <message>
      <source>PREF_SHOW_COLOR_LEGEND</source>
      <translation>色の凡例を表示します。</translation>
    </message>
    <message>
      <source>TIT_PVISSETTINGS</source>
      <translation>ParaVis オプション</translation>
    </message>
    <message>
      <source>TIT_PVIEWSETTINGS</source>
      <translation>ParaView オプション</translation>
    </message>
    <message>
      <source>MEN_MACROS</source>
      <translation>マクロ(&amp;M)</translation>
    </message>
    <message>
      <source>PREF_SAVE_TYPE_LBL</source>
      <translation>型の状態の Paraview の記録</translation>
    </message>
    <message>
      <source>PREF_SAVE_TYPE_0</source>
      <translation>掲示板サーバーだけに参照ファイルを保存します。</translation>
    </message>
    <message>
      <source>PREF_SAVE_TYPE_1</source>
      <translation>アクセス可能な場合は常に参照のファイルを保存します。</translation>
    </message>
    <message>
      <source>PREF_SAVE_TYPE_2</source>
      <translation>参照ファイルを保存します。</translation>
    </message>
    <message>
      <source>MEN_NEW_PV_VIEW</source>
      <translation>ParaViewビュー</translation>
    </message>
    <message>
      <source>MEN_SAVE_MULTI_STATE</source>
      <translation>状態を保存します。</translation>
    </message>
    <message>
      <source>MEN_ADD_STATE</source>
      <translation>状態を追加</translation>
    </message>
    <message>
      <source>MEN_CLEAN_ADD_STATE</source>
      <translation>削除し、状態を追加</translation>
    </message>
    <message>
      <source>MEN_PARAVIS_RENAME</source>
      <translation>名前変更</translation>
    </message>
    <message>
      <source>MEN_PARAVIS_DELETE</source>
      <translation>削除</translation>
    </message>
    <message>
      <source>SAVED_PARAVIEW_STATE_NAME</source>
      <translation>Paraview の状態:</translation>
    </message>
    <message>
      <source>ERR_ERROR</source>
      <translation>エラー</translation>
    </message>
    <message>
      <source>ERR_STATE_CANNOT_BE_RESTORED</source>
      <translation>状態を復元できません。</translation>
    </message>
  </context>
</TS>
