<!DOCTYPE TS><TS>
<context>
    <name>@default</name>
    <message>
        <source>ICON_PARAVIS</source>
        <translation>pqAppIcon22.png</translation>
    </message>
    <message>
        <source>ICON_OPEN_FILE</source>
        <translation>pqOpen24.png</translation>
    </message>
    <message>
        <source>ICON_SAVE_DATA</source>
        <translation>pqSave24.png</translation>
    </message>
    <message>
        <source>ICON_SAVE_SCREENSHOT</source>
        <translation>pqCaptureScreenshot24.png</translation>
    </message>
    <message>
        <source>ICON_SAVE_ANIMATION</source>
        <translation>pqSaveAnimation24.png</translation>
    </message>
    <message>
        <source>ICON_CONNECT</source>
        <translation>pqConnect24.png</translation>
    </message>
    <message>
        <source>ICON_DISCONNECT</source>
        <translation>pqDisconnect24.png</translation>
    </message>
    <message>
        <source>ICON_UNDO</source>
        <translation>pqUndo24.png</translation>
    </message>
    <message>
        <source>ICON_REDO</source>
        <translation>pqRedo24.png</translation>
    </message>
    <message>
        <source>ICON_CAMERA_UNDO</source>
        <translation>pqUndoCamera24.png</translation>
    </message>
    <message>
        <source>ICON_CAMERA_REDO</source>
        <translation>pqRedoCamera24.png</translation>
    </message>
    <message>
        <source>ICON_INTERACT</source>
        <translation>pqRotate24.png</translation>
    </message>
    <message>
        <source>ICON_SELECT_CELLS_ON</source>
        <translation>pqSurfaceSelectionCell24.png</translation>
    </message>
    <message>
        <source>ICON_SELECT_POINTS_ON</source>
        <translation>pqSurfaceSelectionPoint24.png</translation>
    </message>
    <message>
        <source>ICON_SELECT_CELLS_THROUGH</source>
        <translation>pqFrustumSelectionCell24.png</translation>
    </message>
    <message>
        <source>ICON_SELECT_POINTS_THROUGH</source>
        <translation>pqFrustumSelectionPoint24.png</translation>
    </message>
    <message>
        <source>ICON_SELECT_BLOCK</source>
        <translation>pqGroupExtract24.png</translation>
    </message>
    <message>
        <source>ICON_RESET_CAMERA</source>
        <translation>pqResetCamera24.png</translation>
    </message>
    <message>
        <source>ICON_+X</source>
        <translation>pqXPlus24.png</translation>
    </message>
    <message>
        <source>ICON_-X</source>
        <translation>pqXMinus24.png</translation>
    </message>
    <message>
        <source>ICON_+Y</source>
        <translation>pqYPlus24.png</translation>
    </message>
    <message>
        <source>ICON_-Y</source>
        <translation>pqYMinus24.png</translation>
    </message>
    <message>
        <source>ICON_+Z</source>
        <translation>pqZPlus24.png</translation>
    </message>
    <message>
        <source>ICON_-Z</source>
        <translation>pqZMinus24.png</translation>
    </message>
    <message>
        <source>ICON_SHOW_CENTER</source>
        <translation>pqShowCenterAxes24.png</translation>
    </message>
    <message>
        <source>ICON_RESET_CENTER</source>
        <translation>pqResetCenter24.png</translation>
    </message>
    <message>
        <source>ICON_PICK_CENTER</source>
        <translation>pqPickCenter24.png</translation>
    </message>
    <message>
        <source>ICON_SHOW_COLOR_LEGEND</source>
        <translation>pqScalarBar24.png</translation>
    </message>
    <message>
        <source>ICON_EDIT_COLOR_MAP</source>
        <translation>pqEditColor24.png</translation>
    </message>
    <message>
        <source>ICON_RESET_RANGE</source>
        <translation>pqResetRange24.png</translation>
    </message>
    <message>
        <source>ICON_FIRST_FRAME</source>
        <translation>pqVcrFirst24.png</translation>
    </message>
    <message>
        <source>ICON_PREVIOUS_FRAME</source>
        <translation>pqVcrBack24.png</translation>
    </message>
    <message>
        <source>ICON_PLAY</source>
        <translation>pqVcrPlay24.png</translation>
    </message>
    <message>
        <source>ICON_PAUSE</source>
        <translation>pqVcrPause24.png</translation>
    </message>
    <message>
        <source>ICON_NEXT_FRAME</source>
        <translation>pqVcrForward24.png</translation>
    </message>
    <message>
        <source>ICON_LAST_FRAME</source>
        <translation>pqVcrLast24.png</translation>
    </message>
    <message>
        <source>ICON_LOOP</source>
        <translation>pqVcrLoop24.png</translation>
    </message>
    <message>
        <source>ICON_PARAVIEW_HELP</source>
        <translation>pqHelp24.png</translation>
    </message>
    
</context>
</TS>
